name: CI - Data-Gen project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies via uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv install -r requirements.txt
          uv install pytest pytest-cov httpx uvicorn ruff

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: |
          ruff check app tests

      - name: Run unit tests
        run: |
          uv run pytest tests/test_api.py --maxfail=1 --disable-warnings -v

      - name: Run HTTP API tests
        run: |
          uv run pytest tests/test_api_http.py --maxfail=1 --disable-warnings -v
