name: CI - Data-Gen project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies via uv
        run: |
          uv install -r requirements.txt
          uv install pytest pytest-cov httpx uvicorn ruff

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: |
          ruff check app tests

      - name: Run unit tests
        run: |
          uv run pytest tests/test_api.py --maxfail=1 --disable-warnings -v

      - name: Run HTTP API tests
        run: |
          uv run pytest tests/test_api_http.py --maxfail=1 --disable-warnings -v

      - name: Run coverage
        run: |
          uv run pytest --cov=app tests/ --cov-report=xml --cov-report=html

      - name: Generate HTML coverage report
        run: |
          pytest --cov=app tests/ --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

  publish-coverage:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download HTML coverage report
        uses: actions/download-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: htmlcov
